name: HTTP Request to Vester on pull_request for visual testing

on:
  pull_request:
    branches: [ "vester_visual_testing" ]


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Make Request
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://mk7.tech:13117/Vester/API'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Accept": "application/json, text/plain, */*"}'
        #data: '{"token": ${{ secrets.VESTER_TOKEN }}, "repository_url": "https://github.com/IVAN-MK7/egui", "repository_branch_name": "vester_visual_testing"}'
        data: '{"token": "${{ secrets.VESTER_TOKEN }}", "repository_url": "${{ github.event.pull_request.head.repo.html_url }}", "repository_branch_name": "${{ github.event.pull_request.head.ref }}"}'
        timeout: 400000

    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ github.ref }}

    - name: Check scan result
      #if: ${{ fromJson(steps.myRequest.outputs.response).text != 'Token is valid, process executed, scan passed' }}
      if: ${{ !fromJson(steps.myRequest.outputs.response).success }}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Scan failed, response: ${{ steps.myRequest.outputs.response }}')
