name: HTTP Request to Vester on pull_request for visual testing

on:
  pull_request:
    branches: [ "vester_visual_testing" ]


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Make Request
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.EGUI_DEMO_TESTING_URL }}
        method: 'POST'
        customHeaders: |
          "Content-Type": "application/json"
          "Accept": "application/json, text/plain, */*"
        #"repository_url_and_branch": ["https://github.com/IVAN-MK7/egui", "master"]
        data: |
          {
            "env_gen_id": "${{ secrets.EGUI_APP_DEMO_ENV_GEN_ID }}",
            "repository_url_and_branch": ["${{ github.event.pull_request.head.repo.html_url }}", "${{ github.event.pull_request.head.ref }}"]
          }
        timeout: 1000000

    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ github.ref }}

    - name: Check scan result
      #if: ${{ fromJson(steps.myRequest.outputs.response).text != 'Environment Generator found, process executed, scan passed. Vester Task ran to completion.' }}
      if: ${{ !fromJson(steps.myRequest.outputs.response).success }}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Scan failed, response: ${{ steps.myRequest.outputs.response }}')
